# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqlifZf9yH_MGPAwsKsp8Eo5m2EEDk0N
"""



import PyPDF2
import openai

openai.api_key = ''
def extract_text_from_pdf(pdf_file):
    """Extract text from a PDF file."""
    text = ""
    with open(pdf_file, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text() + "\n"
    return text

def get_answer(question, context):
    """Get answer from OpenAI API based on the question and context."""
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": f"Context: {context}\n\nQuestion: {question}"}
        ],
        max_tokens=150
    )
    return response['choices'][0]['message']['content']







0# Step 6.1: Extract text from the uploaded PDF
context = extract_text_from_pdf(pdf_file)

# Step 6.2: Ask a question about the PDF
question = input("Enter your question about the PDF: ")

# Step 6.3: Get the answer from OpenAI
answer = get_answer(question, context)

# Step 6.4: Print the answer
print("Answer:", answer)

# Import necessary libraries
from gtts import gTTS
from IPython.display import Audio

def text_to_speech(text, lang='en'):
    # Create a gTTS object
    tts = gTTS(text=text, lang=lang, slow=False)

    # Save the audio file
    filename = "output.mp3"
    tts.save(filename)
    print(f"Audio saved as {filename}")

    # Play the audio file
    return Audio(filename, autoplay=True)

# Get user input and convert to speech
user_text = answer
audio_output = text_to_speech(user_text)
audio_output

